export const edexcelPhysicsQuestions = [
  {
    text: "What is the name of the galaxy that contains our Solar System?",
    choices: JSON.stringify([
      "Andromeda",
      "Milky Way",
      "Sombrero",
      "Triangulum",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Astrophysics",
  },
  {
    text: "What is the primary factor that determines the colour of a star?",
    choices: JSON.stringify([
      "Its age",
      "Its distance from Earth",
      "Its surface temperature",
      "Its size",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Astrophysics",
  },
  {
    text: "Which of the following best describes the lifecycle of a star much larger than our Sun?",
    choices: JSON.stringify([
      "It becomes a white dwarf",
      "It becomes a neutron star or black hole",
      "It remains stable",
      "It burns out and disappears",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Astrophysics",
  },
  {
    text: "What is the force that keeps planets in orbit around the Sun?",
    choices: JSON.stringify([
      "Electromagnetic force",
      "Gravitational force",
      "Nuclear force",
      "Centrifugal force",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Astrophysics",
  },
  {
    text: "Which of the following describes the Big Bang Theory?",
    choices: JSON.stringify([
      "A theory about the formation of black holes",
      "A theory describing the origin of the universe",
      "A theory about the lifecycle of stars",
      "A theory about the motion of galaxies",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Astrophysics",
  },
  {
    text: "What is a light-year?",
    choices: JSON.stringify([
      "The distance light travels in one year",
      "The time it takes for light to travel around Earth",
      "The time it takes for light to reach the nearest star",
      "The speed of light in a vacuum",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Astrophysics",
  },
  {
    text: "Which of the following best describes a comet?",
    choices: JSON.stringify([
      "A rocky object in the asteroid belt",
      "A small icy body that orbits the Sun",
      "A planetesimal from the early solar system",
      "A cloud of gas in the Milky Way",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Astrophysics",
  },
  {
    text: "What causes the seasons on Earth?",
    choices: JSON.stringify([
      "The distance of Earth from the Sun",
      "The tilt of Earth's axis",
      "The shape of Earth's orbit",
      "The rotation of Earth",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Astrophysics",
  },
  {
    text: "What is the surface temperature of the Sun approximately?",
    choices: JSON.stringify(["3,000 K", "5,800 K", "10,000 K", "15,000 K"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Astrophysics",
  },
  {
    text: "Which type of star is most likely to end its life as a supernova?",
    choices: JSON.stringify([
      "Red dwarf",
      "Main sequence star",
      "Giant star",
      "Massive star",
    ]),
    correctAnswer: 3,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Astrophysics",
  },
  {
    text: "What is the Cosmic Microwave Background Radiation?",
    choices: JSON.stringify([
      "Radiation from a distant galaxy",
      "Radiation from the Sun",
      "Leftover radiation from the Big Bang",
      "Radiation from a supernova",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Astrophysics",
  },
  {
    text: "Which type of telescope is most commonly used to observe distant galaxies?",
    choices: JSON.stringify([
      "Optical telescope",
      "Radio telescope",
      "X-ray telescope",
      "Infrared telescope",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Astrophysics",
  },
  {
    text: "What is the primary source of energy for the Sun?",
    choices: JSON.stringify([
      "Chemical reactions",
      "Nuclear fission",
      "Nuclear fusion",
      "Gravitational collapse",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Astrophysics",
  },
  {
    text: "Which planet in our solar system has the largest number of moons?",
    choices: JSON.stringify(["Earth", "Mars", "Jupiter", "Saturn"]),
    correctAnswer: 3,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Astrophysics",
  },
  {
    text: "What is the name of the nearest star to Earth after the Sun?",
    choices: JSON.stringify([
      "Proxima Centauri",
      "Sirius",
      "Betelgeuse",
      "Alpha Centauri",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Astrophysics",
  },
  {
    text: "What is the main factor that prevents the gravitational collapse of a main sequence star?",
    choices: JSON.stringify([
      "Electromagnetic force",
      "Nuclear fusion pressure",
      "Thermal radiation",
      "Magnetic fields",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Astrophysics",
  },
  {
    text: "Which of the following defines absolute zero?",
    choices: JSON.stringify([
      "The temperature at which water freezes",
      "The temperature at which all molecular motion stops",
      "The temperature at which gas pressure is highest",
      "The lowest temperature ever recorded on Earth",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "Which law describes the relationship between the pressure and volume of a gas at constant temperature?",
    choices: JSON.stringify([
      "Boyle's Law",
      "Charles's Law",
      "Gay-Lussac's Law",
      "Avogadro's Law",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "What is the SI unit of specific heat capacity?",
    choices: JSON.stringify(["J/kg", "J/kg°C", "J/mol", "J/kg·m"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "What happens to the internal energy of a gas when it is compressed?",
    choices: JSON.stringify([
      "It increases",
      "It decreases",
      "It remains the same",
      "It becomes zero",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "Which of the following processes involves the transfer of thermal energy by the movement of a fluid?",
    choices: JSON.stringify([
      "Conduction",
      "Convection",
      "Radiation",
      "Sublimation",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "What is the primary mechanism of heat transfer in a vacuum?",
    choices: JSON.stringify([
      "Conduction",
      "Convection",
      "Radiation",
      "Condensation",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "Which of the following best describes latent heat?",
    choices: JSON.stringify([
      "The energy required to change the temperature of a substance",
      "The energy required to change the state of a substance without changing its temperature",
      "The energy released when a substance cools down",
      "The energy absorbed by a substance during photosynthesis",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "What happens to the pressure of a fixed mass of gas if its temperature increases while the volume remains constant?",
    choices: JSON.stringify([
      "It increases",
      "It decreases",
      "It remains constant",
      "It becomes zero",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "Which of the following quantities increases as the temperature of a substance increases?",
    choices: JSON.stringify([
      "Potential energy of particles",
      "Kinetic energy of particles",
      "Mass of the substance",
      "Volume of the substance",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "Which of the following describes Charles's Law?",
    choices: JSON.stringify([
      "The pressure of a gas is inversely proportional to its volume",
      "The volume of a gas is directly proportional to its temperature at constant pressure",
      "The pressure of a gas is directly proportional to its temperature",
      "The volume of a gas is inversely proportional to its temperature",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "What is the specific latent heat of fusion?",
    choices: JSON.stringify([
      "The energy required to melt a substance at its melting point",
      "The energy required to raise the temperature of a substance by 1°C",
      "The energy required to change the state of a substance from solid to gas",
      "The energy required to cool a substance to absolute zero",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "Which of the following best describes thermal equilibrium?",
    choices: JSON.stringify([
      "When two objects have the same temperature",
      "When two objects have the same thermal conductivity",
      "When heat flows from the hotter object to the cooler object",
      "When the specific heat capacity of two objects is the same",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "What is the Kelvin temperature scale primarily used for?",
    choices: JSON.stringify([
      "Measuring temperatures below zero Celsius",
      "Calculating gas laws and absolute temperatures",
      "Everyday temperature measurements",
      "Measuring heat energy in food",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "What happens to the temperature of a gas during an adiabatic expansion?",
    choices: JSON.stringify([
      "It increases",
      "It decreases",
      "It remains constant",
      "It becomes zero",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "Which of the following best describes an alpha particle?",
    choices: JSON.stringify([
      "A helium nucleus",
      "An electron",
      "A neutron",
      "A photon",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What happens to the current in a circuit if the resistance is doubled while the voltage remains constant?",
    choices: JSON.stringify([
      "It doubles",
      "It halves",
      "It remains the same",
      "It becomes zero",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "Which device is used to convert mechanical energy into electrical energy?",
    choices: JSON.stringify(["Motor", "Generator", "Battery", "Capacitor"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Magnetism",
  },
  {
    text: "Which of the following waves can travel through a vacuum?",
    choices: JSON.stringify([
      "Sound wave",
      "Water wave",
      "Light wave",
      "Seismic wave",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which physical quantity is measured in tesla?",
    choices: JSON.stringify([
      "Magnetic flux",
      "Magnetic field strength",
      "Electric field strength",
      "Inductance",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Magnetism",
  },
  {
    text: "What is the unit of power in the SI system?",
    choices: JSON.stringify(["Watt", "Joule", "Newton", "Pascal"]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Energy Resources and Transfers",
  },
  {
    text: "What is the phenomenon where light spreads out after passing through a narrow opening?",
    choices: JSON.stringify([
      "Reflection",
      "Refraction",
      "Diffraction",
      "Interference",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which type of radiation is the most ionising?",
    choices: JSON.stringify(["Alpha", "Beta", "Gamma", "Neutron"]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is the role of the neutron in the nucleus of an atom?",
    choices: JSON.stringify([
      "To attract electrons",
      "To provide a positive charge",
      "To add mass and provide stability",
      "To produce light",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Which of the following is true about the direction of the magnetic field lines around a bar magnet?",
    choices: JSON.stringify([
      "They go from south to north",
      "They go from north to south",
      "They are circular around the magnet",
      "They are perpendicular to the magnet",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Magnetism",
  },
  {
    text: "What happens to the speed of a wave when it passes from a less dense to a more dense medium?",
    choices: JSON.stringify([
      "It increases",
      "It decreases",
      "It remains the same",
      "It becomes zero",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which quantity is represented by the slope of a distance-time graph?",
    choices: JSON.stringify([
      "Speed",
      "Acceleration",
      "Force",
      "Energy Resources and Transfers",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "Which of the following materials is a good insulator?",
    choices: JSON.stringify(["Copper", "Silver", "Plastic", "Iron"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "Which law states that the force between two point charges is inversely proportional to the square of the distance between them?",
    choices: JSON.stringify([
      "Ohm's Law",
      "Coulomb's Law",
      "Hooke's Law",
      "Newton's Law",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What is the main energy conversion in a hydroelectric power station?",
    choices: JSON.stringify([
      "Kinetic to electrical",
      "Thermal to electrical",
      "Chemical to electrical",
      "Nuclear to electrical",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Energy Resources and Transfers",
  },
  {
    text: "What is the effect of increasing the number of coils in a solenoid?",
    choices: JSON.stringify([
      "The magnetic field strength increases",
      "The magnetic field strength decreases",
      "The current decreases",
      "The current increases",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Magnetism",
  },
  {
    text: "What happens to the wavelength of light as it passes from air to glass?",
    choices: JSON.stringify([
      "It increases",
      "It decreases",
      "It remains the same",
      "It becomes zero",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which physical quantity is represented by the area under a force-time graph?",
    choices: JSON.stringify(["Momentum", "Energy", "Impulse", "Power"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "What is the primary function of a transformer in a power distribution system?",
    choices: JSON.stringify([
      "To step up or step down voltage",
      "To convert AC to DC",
      "To store electrical energy",
      "To measure electrical energy",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Magnetism",
  },
  {
    text: "Which of the following statements is true about sound waves?",
    choices: JSON.stringify([
      "They are longitudinal waves",
      "They can travel through a vacuum",
      "They are electromagnetic waves",
      "They do not require a medium",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which type of energy is stored in a compressed spring?",
    choices: JSON.stringify([
      "Kinetic energy",
      "Gravitational potential energy",
      "Elastic potential energy",
      "Thermal energy",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Energy Resources and Transfers",
  },
  {
    text: "Which of the following best describes the principle of conservation of momentum?",
    choices: JSON.stringify([
      "Momentum is always conserved in an isolated system",
      "Momentum can be created or destroyed",
      "Momentum depends on external forces",
      "Momentum increases over time",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "Which of the following describes the movement of electrons in a conductor?",
    choices: JSON.stringify([
      "From positive to negative",
      "From negative to positive",
      "In random directions",
      "They do not move",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What is the SI unit of electric potential difference?",
    choices: JSON.stringify(["Coulomb", "Ampere", "Volt", "Watt"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What is the function of a capacitor in an electrical circuit?",
    choices: JSON.stringify([
      "To store electrical energy",
      "To increase current",
      "To decrease voltage",
      "To convert AC to DC",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "Which of the following particles is negatively charged?",
    choices: JSON.stringify(["Proton", "Electron", "Neutron", "Photon"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is the speed of sound in air at room temperature?",
    choices: JSON.stringify(["340 m/s", "1500 m/s", "3000 m/s", "5000 m/s"]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "What is the principle behind the operation of a generator?",
    choices: JSON.stringify([
      "Electromagnetic induction",
      "Thermoelectric effect",
      "Photoelectric effect",
      "Electromagnetic radiation",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Magnetism",
  },
  {
    text: "Which of the following is a non-renewable energy source?",
    choices: JSON.stringify(["Solar", "Wind", "Geothermal", "Coal"]),
    correctAnswer: 3,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Energy Resources and Transfers",
  },
  {
    text: "What happens to the density of a substance as it is heated and expands?",
    choices: JSON.stringify([
      "It increases",
      "It decreases",
      "It remains constant",
      "It becomes zero",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "What is the main function of a battery in a circuit?",
    choices: JSON.stringify([
      "To convert electrical energy to chemical energy",
      "To provide a potential difference",
      "To reduce current",
      "To increase resistance",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "Which physical quantity is measured in coulombs?",
    choices: JSON.stringify([
      "Energy Resources and Transfers",
      "Power",
      "Charge",
      "Resistance",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What is the energy conversion that takes place in a microphone?",
    choices: JSON.stringify([
      "Electrical to sound",
      "Sound to electrical",
      "Sound to light",
      "Electrical to light",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which of the following is true about a convex lens?",
    choices: JSON.stringify([
      "It diverges light rays",
      "It focuses light rays to a point",
      "It reflects light rays",
      "It disperses light into colours",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "What happens to the voltage across a resistor if the current flowing through it is doubled?",
    choices: JSON.stringify([
      "It doubles",
      "It halves",
      "It remains the same",
      "It becomes zero",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "Which of the following forces opposes the relative motion of two surfaces in contact?",
    choices: JSON.stringify([
      "Gravitational force",
      "Electrostatic force",
      "Magnetic force",
      "Frictional force",
    ]),
    correctAnswer: 3,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "What type of image is formed by a convex lens when the object is placed beyond the focal point?",
    choices: JSON.stringify([
      "Virtual and upright",
      "Virtual and inverted",
      "Real and inverted",
      "Real and upright",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "What is the function of a relay in an electrical circuit?",
    choices: JSON.stringify([
      "To amplify the current",
      "To open or close a circuit remotely",
      "To store electrical energy",
      "To reduce voltage",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Magnetism",
  },
  {
    text: "What is the effect of increasing the frequency of a sound wave?",
    choices: JSON.stringify([
      "The pitch of the sound increases",
      "The pitch of the sound decreases",
      "The sound becomes louder",
      "The sound becomes quieter",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which physical quantity is conserved in an isolated system?",
    choices: JSON.stringify([
      "Force",
      "Energy Resources and Transfers",
      "Velocity",
      "Acceleration",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "What is the purpose of insulation in electrical wiring?",
    choices: JSON.stringify([
      "To increase the current",
      "To prevent electric shocks",
      "To reduce resistance",
      "To store charge",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "Which type of mirror is used in a car's rearview mirror to provide a wider field of view?",
    choices: JSON.stringify([
      "Plane mirror",
      "Concave mirror",
      "Convex mirror",
      "Cylindrical mirror",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "What happens to the kinetic energy of an object if its velocity is doubled?",
    choices: JSON.stringify([
      "It remains the same",
      "It doubles",
      "It quadruples",
      "It halves",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Energy Resources and Transfers",
  },
  {
    text: "Which of the following is an example of a mechanical wave?",
    choices: JSON.stringify([
      "Light wave",
      "Radio wave",
      "Sound wave",
      "Gamma rays",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which device is used to measure the potential difference between two points in a circuit?",
    choices: JSON.stringify([
      "Ammeter",
      "Voltmeter",
      "Ohmmeter",
      "Galvanometer",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What is the process by which heat is transferred through direct contact of particles?",
    choices: JSON.stringify([
      "Convection",
      "Radiation",
      "Conduction",
      "Evaporation",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "Which of the following devices is used to detect radiation?",
    choices: JSON.stringify([
      "Barometer",
      "Galvanometer",
      "Geiger-Muller tube",
      "Thermometer",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is the role of a moderator in a nuclear reactor?",
    choices: JSON.stringify([
      "To slow down neutrons",
      "To absorb neutrons",
      "To reflect neutrons",
      "To increase the number of neutrons",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What happens to the pressure in a liquid as the depth increases?",
    choices: JSON.stringify([
      "It increases",
      "It decreases",
      "It remains constant",
      "It becomes zero",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "Which physical quantity is defined as the rate of doing work?",
    choices: JSON.stringify([
      "Energy Resources and Transfers",
      "Power",
      "Force",
      "Momentum",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Energy Resources and Transfers",
  },
  {
    text: "Which of the following particles is found in the nucleus of an atom?",
    choices: JSON.stringify(["Electron", "Proton", "Neutrino", "Photon"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is the main purpose of an earth wire in an electrical system?",
    choices: JSON.stringify([
      "To supply power",
      "To reduce power loss",
      "To provide a return path for current",
      "To prevent electric shocks",
    ]),
    correctAnswer: 3,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "Which type of radiation has no mass and no charge?",
    choices: JSON.stringify([
      "Alpha particles",
      "Beta particles",
      "Gamma rays",
      "Neutrons",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is the device that measures electric current called?",
    choices: JSON.stringify([
      "Ammeter",
      "Voltmeter",
      "Ohmmeter",
      "Thermometer",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "Which of the following is a correct unit of pressure?",
    choices: JSON.stringify(["Joule", "Watt", "Pascal", "Newton"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "What is the potential energy of an object at height h above the ground?",
    choices: JSON.stringify(["mgh", "1/2mv²", "mg/h", "m/h"]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Energy Resources and Transfers",
  },
  {
    text: "Which of the following is used to reduce friction in machines?",
    choices: JSON.stringify(["Lubricant", "Spring", "Pulley", "Lever"]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "Which law explains the buoyant force experienced by an object submerged in a fluid?",
    choices: JSON.stringify([
      "Newton's First Law",
      "Boyle's Law",
      "Archimedes' Principle",
      "Hooke's Law",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "What is the effect of increasing the temperature of a gas at constant volume?",
    choices: JSON.stringify([
      "Pressure decreases",
      "Pressure increases",
      "Pressure remains constant",
      "Pressure becomes zero",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "Which of the following types of energy is stored in a compressed spring?",
    choices: JSON.stringify([
      "Kinetic energy",
      "Elastic potential energy",
      "Thermal energy",
      "Chemical energy",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Energy Resources and Transfers",
  },
  {
    text: "What is the unit of electrical current?",
    choices: JSON.stringify(["Coulomb", "Volt", "Ampere", "Watt"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "Which component in an electric circuit is used to prevent the flow of current beyond a certain value?",
    choices: JSON.stringify(["Resistor", "Capacitor", "Fuse", "Transformer"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What is the relationship between pressure and volume of a gas at constant temperature?",
    choices: JSON.stringify([
      "Directly proportional",
      "Inversely proportional",
      "No relationship",
      "Exponentially proportional",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "What is the phenomenon where light changes direction as it passes from one medium to another called?",
    choices: JSON.stringify([
      "Reflection",
      "Refraction",
      "Diffraction",
      "Dispersion",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which of the following quantities is conserved in an inelastic collision?",
    choices: JSON.stringify([
      "Kinetic energy",
      "Momentum",
      "Velocity",
      "Acceleration",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "Which of the following materials is commonly used as a conductor in electrical circuits?",
    choices: JSON.stringify(["Glass", "Rubber", "Plastic", "Copper"]),
    correctAnswer: 3,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What happens to the boiling point of water as atmospheric pressure decreases?",
    choices: JSON.stringify([
      "It increases",
      "It decreases",
      "It remains the same",
      "It becomes zero",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "Which of the following forces acts on an object moving in a circular path and is directed toward the centre of the circle?",
    choices: JSON.stringify([
      "Centrifugal force",
      "Centripetal force",
      "Gravitational force",
      "Frictional force",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "Which device is used to step up or step down voltage in an AC circuit?",
    choices: JSON.stringify(["Rectifier", "Transformer", "Inductor", "Diode"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What type of current flows in one direction only?",
    choices: JSON.stringify([
      "Alternating current",
      "Direct current",
      "Pulsating current",
      "Rotating current",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "Which physical quantity is measured in joules per second?",
    choices: JSON.stringify([
      "Power",
      "Energy Resources and Transfers",
      "Force",
      "Pressure",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Energy Resources and Transfers",
  },
  {
    text: "Which of the following describes the function of a galvanometer?",
    choices: JSON.stringify([
      "Measures electric current",
      "Measures potential difference",
      "Measures resistance",
      "Measures magnetic field strength",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What is the effect of a magnetic field on a moving charge?",
    choices: JSON.stringify([
      "It experiences a force perpendicular to both the field and velocity",
      "It moves in the direction of the field",
      "It remains stationary",
      "Its velocity decreases",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Magnetism",
  },
  {
    text: "Which of the following quantities is equal to the product of mass and velocity?",
    choices: JSON.stringify([
      "Force",
      "Energy Resources and Transfers",
      "Momentum",
      "Power",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "What happens to the frequency of a wave if the speed of the wave increases while the wavelength remains constant?",
    choices: JSON.stringify([
      "It increases",
      "It decreases",
      "It remains the same",
      "It becomes zero",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "What is the SI unit of frequency?",
    choices: JSON.stringify(["Watt", "Coulomb", "Hertz", "Volt"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which of the following best describes a scalar quantity?",
    choices: JSON.stringify([
      "Has only magnitude",
      "Has only direction",
      "Has both magnitude and direction",
      "Changes over time",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "What is the primary function of a diode in a circuit?",
    choices: JSON.stringify([
      "To store charge",
      "To allow current to flow in one direction",
      "To increase voltage",
      "To convert AC to DC",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What is the law that states that current is directly proportional to voltage across a conductor at constant temperature?",
    choices: JSON.stringify([
      "Ohm's Law",
      "Boyle's Law",
      "Hooke's Law",
      "Newton's First Law",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What happens to the resistance of a conductor as its temperature increases?",
    choices: JSON.stringify([
      "It increases",
      "It decreases",
      "It remains the same",
      "It becomes zero",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "Which of the following waves requires a medium to propagate?",
    choices: JSON.stringify([
      "Light waves",
      "Radio waves",
      "Sound waves",
      "X-rays",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "What is the energy of an object due to its motion called?",
    choices: JSON.stringify([
      "Potential energy",
      "Kinetic energy",
      "Thermal energy",
      "Chemical energy",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Energy Resources and Transfers",
  },
  {
    text: "Which type of electromagnetic wave is most commonly used in mobile phone communications?",
    choices: JSON.stringify([
      "Microwaves",
      "Infrared",
      "Ultraviolet",
      "X-rays",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Magnetism",
  },
  {
    text: "What is the relationship between force and acceleration according to Newton's second law?",
    choices: JSON.stringify(["F = ma", "F = mv", "F = m/a", "F = m/v"]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "Which part of an atom is positively charged?",
    choices: JSON.stringify(["Proton", "Neutron", "Electron", "Nucleus"]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Which type of lens is used to magnify objects?",
    choices: JSON.stringify([
      "Concave lens",
      "Convex lens",
      "Cylindrical lens",
      "Bifocal lens",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "What type of wave is light?",
    choices: JSON.stringify([
      "Longitudinal",
      "Transverse",
      "Compression",
      "Mechanical",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which of the following describes the motion of an object under free fall near the Earth's surface?",
    choices: JSON.stringify([
      "It moves with constant speed",
      "It accelerates at 9.8 m/s²",
      "Its acceleration decreases",
      "It moves upward",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "Which instrument is used to measure atmospheric pressure?",
    choices: JSON.stringify([
      "Thermometer",
      "Barometer",
      "Voltmeter",
      "Manometer",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Solids, Liquids and Gases",
  },
  {
    text: "What is the time taken for one complete cycle of a wave called?",
    choices: JSON.stringify(["Frequency", "Period", "Amplitude", "Wavelength"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which of the following is not an electromagnetic wave?",
    choices: JSON.stringify([
      "X-rays",
      "Gamma rays",
      "Sound waves",
      "Microwaves",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "What does a voltmeter measure?",
    choices: JSON.stringify(["Current", "Voltage", "Resistance", "Power"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "In which type of circuit is the total resistance equal to the sum of the individual resistances?",
    choices: JSON.stringify([
      "Series circuit",
      "Parallel circuit",
      "Mixed circuit",
      "Short circuit",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "Which of the following is true about the magnetic field inside a solenoid?",
    choices: JSON.stringify([
      "It is zero",
      "It is uniform",
      "It decreases with distance",
      "It increases with distance",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Magnetism",
  },
  {
    text: "What is the phenomenon where a wave bends as it passes from one medium to another?",
    choices: JSON.stringify([
      "Reflection",
      "Refraction",
      "Diffraction",
      "Interference",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which of the following is a measure of the quantity of matter in an object?",
    choices: JSON.stringify(["Weight", "Mass", "Volume", "Density"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "Which property of a wave is the distance between two consecutive peaks?",
    choices: JSON.stringify(["Frequency", "Wavelength", "Amplitude", "Speed"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which of the following devices can store electrical energy?",
    choices: JSON.stringify(["Resistor", "Capacitor", "Inductor", "Diode"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What happens to the wavelength of a sound wave as its frequency increases?",
    choices: JSON.stringify([
      "It increases",
      "It decreases",
      "It remains constant",
      "It becomes zero",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which of the following is a unit of work?",
    choices: JSON.stringify(["Newton", "Joule", "Watt", "Pascal"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Energy Resources and Transfers",
  },
  {
    text: "What is the effect of increasing the amplitude of a sound wave?",
    choices: JSON.stringify([
      "The sound becomes louder",
      "The sound becomes quieter",
      "The pitch of the sound increases",
      "The pitch of the sound decreases",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "What is the unit of force?",
    choices: JSON.stringify(["Joule", "Newton", "Pascal", "Watt"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "A car accelerates uniformly from rest to 20 m/s in 10 seconds. What is the acceleration of the car?",
    choices: JSON.stringify(["0.5 m/s²", "2 m/s²", "5 m/s²", "10 m/s²"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "Which of the following quantities is a vector?",
    choices: JSON.stringify(["Speed", "Distance", "Velocity", "Mass"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "What is the relationship between voltage, current, and resistance?",
    choices: JSON.stringify([
      "V = I / R",
      "V = I * R",
      "V = R / I",
      "V = I² * R",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "In a series circuit, if one component fails, what happens to the other components?",
    choices: JSON.stringify([
      "They stop working",
      "They continue working",
      "They get damaged",
      "Their resistance decreases",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What is the unit of electrical resistance?",
    choices: JSON.stringify(["Watt", "Coulomb", "Ohm", "Volt"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What type of wave is a sound wave?",
    choices: JSON.stringify([
      "Transverse",
      "Longitudinal",
      "Electromagnetic",
      "Surface",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which part of the electromagnetic spectrum has the longest wavelength?",
    choices: JSON.stringify([
      "Gamma rays",
      "X-rays",
      "Microwaves",
      "Radio waves",
    ]),
    correctAnswer: 3,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Magnetism",
  },
  {
    text: "What is the speed of light in a vacuum?",
    choices: JSON.stringify([
      "3 x 10⁶ m/s",
      "3 x 10⁷ m/s",
      "3 x 10⁸ m/s",
      "3 x 10⁹ m/s",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which of the following is a renewable energy resource?",
    choices: JSON.stringify(["Coal", "Natural Gas", "Wind", "Nuclear"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Energy Resources and Transfers",
  },
  {
    text: "What is the principle of conservation of energy?",
    choices: JSON.stringify([
      "Energy can be created and destroyed",
      "Energy can only be created",
      "Energy cannot be created or destroyed",
      "Energy is always destroyed after use",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Energy Resources and Transfers",
  },
  {
    text: "Which of the following devices is used to reduce unwanted energy transfer?",
    choices: JSON.stringify([
      "Radiator",
      "Conductor",
      "Insulator",
      "Transformer",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Energy Resources and Transfers",
  },
  {
    text: "What is the role of a transformer in the transmission of electrical energy?",
    choices: JSON.stringify([
      "To convert AC to DC",
      "To step up or step down voltage",
      "To store electrical energy",
      "To measure electrical energy",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What happens to a current-carrying wire in a magnetic field?",
    choices: JSON.stringify([
      "It heats up",
      "It experiences a force",
      "It becomes magnetized",
      "It gets charged",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Magnetism",
  },
  {
    text: "Which material is commonly used as the core of an electromagnet?",
    choices: JSON.stringify(["Copper", "Aluminium", "Iron", "Steel"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Magnetism",
  },
  {
    text: "What is the acceleration due to gravity on Earth?",
    choices: JSON.stringify(["9.8 m/s²", "10.0 m/s²", "8.9 m/s²", "7.5 m/s²"]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "What is the SI unit of power?",
    choices: JSON.stringify(["Watt", "Newton", "Joule", "Ampere"]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Energy Resources and Transfers",
  },
  {
    text: "Which law states that the extension of a spring is directly proportional to the force applied?",
    choices: JSON.stringify([
      "Newton's First Law",
      "Hooke's Law",
      "Ohm's Law",
      "Boyle's Law",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "Which of the following quantities is a scalar?",
    choices: JSON.stringify(["Force", "Acceleration", "Velocity", "Speed"]),
    correctAnswer: 3,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "What type of current is supplied to homes and businesses?",
    choices: JSON.stringify([
      "Direct current",
      "Alternating current",
      "Static electricity",
      "Pulsating current",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "Which of the following is true about the speed of sound in different media?",
    choices: JSON.stringify([
      "Faster in air than in water",
      "Faster in a vacuum than in air",
      "Faster in water than in air",
      "Faster in air than in a vacuum",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "What is the primary function of a capacitor in a circuit?",
    choices: JSON.stringify([
      "To store electrical energy",
      "To convert AC to DC",
      "To resist the flow of current",
      "To amplify the signal",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What happens to the frequency of a wave as its wavelength increases?",
    choices: JSON.stringify([
      "It increases",
      "It decreases",
      "It remains constant",
      "It becomes zero",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which type of electromagnetic radiation has the shortest wavelength?",
    choices: JSON.stringify([
      "Radio waves",
      "Microwaves",
      "X-rays",
      "Gamma rays",
    ]),
    correctAnswer: 3,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Magnetism",
  },
  {
    text: "A car accelerates from 0 to 20 m/s in 4 seconds. What is the acceleration of the car?",
    choices: JSON.stringify(["2 m/s²", "4 m/s²", "5 m/s²", "10 m/s²"]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "Which of the following quantities is conserved in an isolated system?",
    choices: JSON.stringify(["Force", "Energy", "Momentum", "Velocity"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "What is the frequency of a wave with a period of 0.5 seconds?",
    choices: JSON.stringify(["0.5 Hz", "1 Hz", "2 Hz", "4 Hz"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "Which type of wave can travel through a vacuum?",
    choices: JSON.stringify([
      "Sound wave",
      "Water wave",
      "Light wave",
      "Seismic wave",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Waves",
  },
  {
    text: "What happens to the resistance of a wire as its temperature increases?",
    choices: JSON.stringify([
      "It increases",
      "It decreases",
      "It remains the same",
      "It becomes zero",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "A circuit has a voltage of 12V and a resistance of 4 ohms. What is the current in the circuit?",
    choices: JSON.stringify(["1 A", "2 A", "3 A", "4 A"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "Which of the following energy resources is non-renewable?",
    choices: JSON.stringify(["Wind", "Solar", "Coal", "Hydroelectric"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Energy Resources and Transfers",
  },
  {
    text: "What is the main energy conversion in a hydroelectric power station?",
    choices: JSON.stringify([
      "Kinetic to electrical",
      "Thermal to electrical",
      "Chemical to electrical",
      "Nuclear to electrical",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Energy Resources and Transfers",
  },
  {
    text: "Which particle has a positive charge?",
    choices: JSON.stringify(["Electron", "Neutron", "Proton", "Photon"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is the role of a moderator in a nuclear reactor?",
    choices: JSON.stringify([
      "To slow down neutrons",
      "To absorb neutrons",
      "To reflect neutrons",
      "To increase the number of neutrons",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is the formula to calculate the force exerted on a spring?",
    choices: JSON.stringify(["F = ma", "F = kx", "F = mv", "F = mgh"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "Which of the following quantities is conserved in an elastic collision?",
    choices: JSON.stringify([
      "Kinetic energy",
      "Momentum",
      "Velocity",
      "Acceleration",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "What is the primary purpose of a moderator in a nuclear reactor?",
    choices: JSON.stringify([
      "To absorb neutrons",
      "To slow down neutrons",
      "To reflect neutrons",
      "To increase the number of neutrons",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Which physical quantity is represented by the area under a force-time graph?",
    choices: JSON.stringify(["Momentum", "Energy", "Impulse", "Power"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "What is the correct unit for momentum?",
    choices: JSON.stringify([
      "kg / m / s",
      "kg m / s",
      "kg m / s²",
      "kg² m / s",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "Which formula represents the power output of an electrical device?",
    choices: JSON.stringify(["P = IV", "P = IR", "P = V/R", "P = VR"]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What does a voltmeter measure?",
    choices: JSON.stringify(["Current", "Voltage", "Resistance", "Power"]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Electricity",
  },
  {
    text: "What is the effect of a magnetic field on a moving charge?",
    choices: JSON.stringify([
      "It experiences a force perpendicular to both the field and velocity",
      "It moves in the direction of the field",
      "It remains stationary",
      "Its velocity decreases",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Magnetism",
  },
  {
    text: "Which of the following best describes a scalar quantity?",
    choices: JSON.stringify([
      "Has only magnitude",
      "Has only direction",
      "Has both magnitude and direction",
      "Changes over time",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "What is the acceleration due to gravity on Earth?",
    choices: JSON.stringify(["9.8 m/s²", "10.0 m/s²", "8.9 m/s²", "7.5 m/s²"]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Forces and Motion",
  },
  {
    text: "What is the half-life of a radioactive isotope?",
    choices: JSON.stringify([
      "The time it takes for half the atoms in a sample to decay",
      "The time it takes for the radioactivity to become zero",
      "The time it takes for all atoms to decay",
      "The time it takes for the energy to halve",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Which of the following particles is emitted during alpha decay?",
    choices: JSON.stringify([
      "A proton",
      "A neutron",
      "An electron",
      "A helium nucleus",
    ]),
    correctAnswer: 3,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is a beta particle?",
    choices: JSON.stringify([
      "A helium nucleus",
      "An electron",
      "A neutron",
      "A gamma ray",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Which type of radiation has the highest penetrating power?",
    choices: JSON.stringify(["Alpha", "Beta", "Gamma", "Neutron"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Which type of radiation is most harmful when ingested?",
    choices: JSON.stringify(["Alpha", "Beta", "Gamma", "Neutron"]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is the main use of radioactive isotopes in medicine?",
    choices: JSON.stringify([
      "For making batteries",
      "For sterilizing equipment",
      "For diagnostic imaging and treatment",
      "For making nuclear bombs",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Which of the following particles is emitted in gamma radiation?",
    choices: JSON.stringify([
      "An electron",
      "A neutron",
      "A proton",
      "A photon",
    ]),
    correctAnswer: 3,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Which material is most effective at stopping gamma radiation?",
    choices: JSON.stringify(["Paper", "Aluminum", "Lead", "Wood"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is nuclear fission?",
    choices: JSON.stringify([
      "The fusion of two light nuclei",
      "The splitting of a heavy nucleus into lighter nuclei",
      "The emission of an alpha particle",
      "The emission of a beta particle",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is the role of a control rod in a nuclear reactor?",
    choices: JSON.stringify([
      "To absorb excess neutrons",
      "To release neutrons",
      "To provide heat",
      "To act as a moderator",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Which type of radiation is used in smoke detectors?",
    choices: JSON.stringify([
      "Alpha radiation",
      "Beta radiation",
      "Gamma radiation",
      "Neutron radiation",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is nuclear fusion?",
    choices: JSON.stringify([
      "The fusion of two light nuclei to form a heavier nucleus",
      "The splitting of a heavy nucleus into lighter nuclei",
      "The emission of gamma rays",
      "The emission of neutrons",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is the effect of beta decay on the atomic number of an element?",
    choices: JSON.stringify([
      "Increases by 1",
      "Decreases by 1",
      "Remains the same",
      "Increases by 2",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Which of the following is a natural source of background radiation?",
    choices: JSON.stringify([
      "Medical X-rays",
      "Cosmic rays",
      "Nuclear power plants",
      "Mobile phones",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is a common unit used to measure radiation dose?",
    choices: JSON.stringify(["Coulomb", "Watt", "Sievert", "Newton"]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Which device is used to detect radioactive particles?",
    choices: JSON.stringify([
      "Barometer",
      "Thermometer",
      "Geiger-Muller tube",
      "Voltmeter",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "How does gamma radiation affect the nucleus of an atom?",
    choices: JSON.stringify([
      "It causes a change in the number of neutrons",
      "It causes a change in the atomic number",
      "It decreases the mass number",
      "It does not change the number of protons or neutrons",
    ]),
    correctAnswer: 3,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What type of radiation is emitted from a nucleus during alpha decay?",
    choices: JSON.stringify([
      "An electron",
      "A proton",
      "A helium nucleus",
      "A neutron",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Which particle is released during neutron emission?",
    choices: JSON.stringify([
      "An alpha particle",
      "A gamma ray",
      "A neutron",
      "A beta particle",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What happens to the mass number of a nucleus after beta decay?",
    choices: JSON.stringify([
      "Increases by 1",
      "Decreases by 1",
      "Remains the same",
      "Increases by 2",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Why are some materials radioactive?",
    choices: JSON.stringify([
      "They contain stable isotopes",
      "Their nuclei are unstable and decay over time",
      "They have a large number of electrons",
      "They have strong magnetic properties",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Which type of radiation is deflected by a magnetic field?",
    choices: JSON.stringify([
      "Alpha radiation",
      "Beta radiation",
      "Gamma radiation",
      "Neutron radiation",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is the primary danger associated with gamma radiation?",
    choices: JSON.stringify([
      "It can cause burns on the skin",
      "It can ionize atoms in living cells, potentially causing cancer",
      "It can cause objects to become magnetized",
      "It can generate electrical currents in metals",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What happens during the process of nuclear decay?",
    choices: JSON.stringify([
      "An atom splits into two or more smaller atoms",
      "An atom releases a particle or energy to become more stable",
      "An atom is absorbed by another atom",
      "An atom loses all of its electrons",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What are cosmic rays?",
    choices: JSON.stringify([
      "Electromagnetic radiation from the sun",
      "High-energy particles from outer space",
      "Reflected light from the moon",
      "Particles emitted from nuclear reactors",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Which of the following isotopes is commonly used in carbon dating?",
    choices: JSON.stringify([
      "Carbon-12",
      "Carbon-14",
      "Carbon-16",
      "Carbon-18",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "How does the intensity of radiation change with distance from the source?",
    choices: JSON.stringify([
      "It remains the same",
      "It decreases with the square of the distance",
      "It doubles with the distance",
      "It increases with the square of the distance",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is the primary use of radon gas in homes?",
    choices: JSON.stringify([
      "For detecting carbon monoxide",
      "For insulating walls",
      "It is not used; it is a hazardous radioactive gas",
      "For providing heating",
    ]),
    correctAnswer: 2,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Which of the following is a characteristic of alpha radiation?",
    choices: JSON.stringify([
      "It has high penetrating power",
      "It is deflected by electric and magnetic fields",
      "It is the least ionizing type of radiation",
      "It travels at the speed of light",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is the role of radiation in the process of radiotherapy?",
    choices: JSON.stringify([
      "To repair damaged cells",
      "To destroy cancerous cells",
      "To generate energy",
      "To sterilize medical equipment",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is meant by radioactive contamination?",
    choices: JSON.stringify([
      "Exposure to radiation from a distance",
      "Presence of radioactive substances on surfaces or within solids, liquids, or gases",
      "Destruction of materials by radioactive decay",
      "Transformation of materials into radioactive forms",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Which particle has the highest mass among alpha, beta, and gamma radiation?",
    choices: JSON.stringify([
      "Alpha particle",
      "Beta particle",
      "Gamma photon",
      "Neutron",
    ]),
    correctAnswer: 0,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "Why is it important to use shielding when working with radioactive materials?",
    choices: JSON.stringify([
      "To prevent theft of materials",
      "To reduce exposure to harmful radiation",
      "To enhance the effect of the radiation",
      "To decrease the half-life of the material",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
  {
    text: "What is the function of a neutron in the nucleus?",
    choices: JSON.stringify([
      "To provide a positive charge",
      "To add mass and provide stability",
      "To attract electrons",
      "To emit radiation",
    ]),
    correctAnswer: 1,
    subject: "Physics",
    level: "IGCSE",
    examBoard: "Edexcel",
    subtopic: "Radioactivity and Particles",
  },
];
